module com.ossobo.winterfx {
    requires transitive javafx.controls;
    requires transitive javafx.fxml;
    requires transitive javafx.graphics;
    requires transitive javafx.base;
    requires transitive javafx.media;

    requires org.slf4j;
    requires org.reflections;
    requires io.github.classgraph;
    requires java.sql;
    requires com.google.gson;
    requires com.google.common;
    requires org.controlsfx.controls;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.core;
    requires org.kordamp.bootstrapfx.core;

    exports com.ossobo.winterfx.bootstrap;
    exports com.ossobo.winterfx.exceptions;
    exports com.ossobo.winterfx.floatingwindow;
    exports com.ossobo.winterfx.di;
    exports com.ossobo.winterfx.di.annotations;
    exports com.ossobo.winterfx.di.annotations.enums;
    exports com.ossobo.winterfx.di.exceptions;
    exports com.ossobo.winterfx.di.scopes;
    exports com.ossobo.winterfx.di.scopes.enums;
    exports com.ossobo.winterfx.di.scanner;
    exports com.ossobo.winterfx.di.scanner.models;
    exports com.ossobo.winterfx.di.reflection;
    exports com.ossobo.winterfx.di.resolver;
    exports com.ossobo.winterfx.di.aot;
    exports com.ossobo.winterfx.resources.descriptor;
    exports com.ossobo.winterfx.resources.enums;
    exports com.ossobo.winterfx.resources.excecoes;
    exports com.ossobo.winterfx.resources.registry;
    exports com.ossobo.winterfx.resources.resolver;
    exports com.ossobo.winterfx.resources.guard;
    exports com.ossobo.winterfx.resources.loader;
    exports com.ossobo.winterfx.resources.cache;
    exports com.ossobo.winterfx.resources.scanner;
    exports com.ossobo.winterfx.view;
    exports com.ossobo.winterfx.view.design;
    exports com.ossobo.winterfx.view.exceptios;
    exports com.ossobo.winterfx.view.loader;
    exports com.ossobo.winterfx.view.refresh;
    exports com.ossobo.winterfx.imagemanager;
    exports com.ossobo.winterfx.imagemanager.image;
    exports com.ossobo.winterfx.notifications;
    exports com.ossobo.winterfx.notifications.model;
    exports com.ossobo.winterfx.notifications.controller;
    exports com.ossobo.winterfx.notifications.resolver;
    exports com.ossobo.winterfx.notifications.exceptions;
    exports com.ossobo.winterfx.notifications.registry;
    exports com.ossobo.winterfx.notifications.core;

    opens com.ossobo.winterfx.view to javafx.fxml;
    opens com.ossobo.winterfx.view.loader to javafx.fxml;
    opens com.ossobo.winterfx.notifications.controller to javafx.fxml;
    opens com.ossobo.winterfx.notifications.model to javafx.fxml;
    opens com.ossobo.winterfx.resources.descriptor to javafx.fxml;
}